### ISSUE TITLE
Error on compiling on debian 11 

### ISSUE THREAD

**Issue by OmniaGit** [python-LimeReport/python-LimeReport#6]
I'm trying to make it works on linux, but during the run of the setup.py i get the following error.

[ 95%] Running generator for /media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xml.
qt.shiboken: (bindings) /media/OneTDisk/virtual_envs/LimeReport/lib/python3.9/site-packages/PySide6/typesystems/typesystem_qml.xml:57:57: Error: File for inject code not exist: ../doc/qtqml_functions.rst
qt.shiboken: (bindings) /media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xml:34:62: Error: Failed to parse: 'typesystem_qml.xml'
Cannot parse file: /media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xmlshiboken: Error running ApiExtractor.

any idea on how to solve it ?
it seems that the file qtqml_functions.rst is not created properly
thanks in advance

**Comment by Maks1mS** [comment]
I am sorry, but I cannot give a quick answer to this question. Could you please provide more details about the environment (package versions etc.)? This would help me to understand the situation better and provide you with a more accurate answer.


You can also check the .github/workflows/wheels.yml file and see if there is any difference between your actions and my. I will also attach the logs from Github Actions for your reference.
[logs_26242011436.zip](https://github.com/user-attachments/files/16323344/logs_26242011436.zip)

**Comment by OmniaGit** [comment]
I'm trying to build it on my linux debian 11 python 3.9, this is the full stack running

`setup.py build --parallel 10 bdist_wheel`

> running build
running build_ext
-- Using python: /media/OneTDisk/virtual_envs/LimeReport/bin/python
-- Qt version: 6
-- QtGui found
-- QtWidgets found
-- STATIC LIBRARY
-- Configuring done
-- Generating done
-- Build files have been written to: /media/OneTDisk/workspace/LimeReport-PythonBinding/build/temp.linux-x86_64-3.9/LimeReport/LimeReport
[  1%] Automatic MOC for target QZint
[  1%] Built target QZint_autogen
[ 27%] Built target QZint
[ 28%] Automatic MOC and UIC for target limereport-qt6
[ 28%] Built target limereport-qt6_autogen
[ 95%] Built target limereport-qt6
[ 95%] Running generator for /media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xml.
qt.shiboken: (bindings) /media/OneTDisk/virtual_envs/LimeReport/lib/python3.9/site-packages/PySide6/typesystems/typesystem_qml.xml:57:57: Error: File for inject code not exist: ../doc/qtqml_functions.rst
qt.shiboken: (bindings) /media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xml:34:62: Error: Failed to parse: 'typesystem_qml.xml'
Cannot parse file: /media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xmlshiboken: Error running ApiExtractor.
Command line:
    "--generator-set=shiboken"
    "--enable-parent-ctor-heuristic"
    "--enable-pyside-extensions"
    "--enable-return-value-heuristic"
    "--use-isnull-as-nb_nonzero"
    "--avoid-protected-hack"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtCore"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtWidgets"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtSql"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtNetwork"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtXml"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtSvg"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtQml"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/x86_64-linux-gnu/qt6/QtPrintSupport"
    "-I/usr/include/x86_64-linux-gnu/qt6"
    "-I/usr/include/c++/10"
    "-I/usr/include/x86_64-linux-gnu/c++/10"
    "-I/usr/include/c++/10/backward"
    "-I/usr/lib/gcc/x86_64-linux-gnu/10/include"
    "-I/usr/local/include"
    "-I/usr/x86_64-linux-gnu/include"
    "-I/usr/include/x86_64-linux-gnu"
    "-I/usr/include"
    "-I/media/OneTDisk/workspace/LimeReport-PythonBinding/LimeReport/include"
    "-T/media/OneTDisk/workspace/LimeReport-PythonBinding"
    "-T/media/OneTDisk/virtual_envs/LimeReport/lib/python3.9/site-packages/PySide6/typesystems"
    "--output-directory=/media/OneTDisk/workspace/LimeReport-PythonBinding/build/temp.linux-x86_64-3.9/LimeReport/LimeReport"
    "/media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.h"
    "/media/OneTDisk/workspace/LimeReport-PythonBinding/bindings.xml"
gmake[2]: *** [CMakeFiles/LimeReport.dir/build.make:83: LimeReport/limereport_module_wrapper.cpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:136: CMakeFiles/LimeReport.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
Traceback (most recent call last):
  File "/media/OneTDisk/workspace/LimeReport-PythonBinding/setup.py", line 203, in <module>
    setup(
  File "/media/OneTDisk/virtual_envs/LimeReport/lib/python3.9/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/OneTDisk/virtual_envs/LimeReport/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.9/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_parallel()
  File "/usr/lib/python3.9/distutils/command/build_ext.py", line 469, in _build_extensions_parallel
    fut.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/media/OneTDisk/workspace/LimeReport-PythonBinding/setup.py", line 184, in build_extension
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j10']' returned non-zero exit status 2.


Thanks in advance
Matteo

**Comment by Maks1mS** [comment]
During my experiments yesterday, I realized that your version of PySide is 6.7 or higher. 

The problem is that in these versions, there is a link to "../doc/qtqml_functions.rst", but I don't see this directory included in the standard PySide installation.

I am currently unsure of the best solution, but you could try manually downloading these files and placing them in the appropriate directory. This might solve the issue. Let me know if that resolves the build issue, and if so, I can add this change to the setup.py file.

https://code.qt.io/cgit/pyside/pyside-setup.git/plain/sources/pyside6/PySide6/doc?h=6.7.0 (replace 6.7.0 with your version)

**Comment by Maks1mS** [comment]
> I can add this change to the setup.py file.

I have already made changes to setup.py file.
If the problem persists, please reopen the issue.
